#!/usr/bin/env python3
"""Generate the reproducible savings table from the shipped fixtures.

This is the single source of truth for the savings numbers quoted in README.md.
Every fixture is run through the *real* compression pipeline (``crux.core.compress``
— processor shaping followed by the optional budget reducer), under both the
default ``balanced`` profile and the ``aggressive`` profile, so the table can
never drift from what a user actually gets.

Usage::

    python tools/generate_demo.py            # print the markdown table + summary
    python tools/generate_demo.py --check     # exit non-zero if README is stale

The ``tests/test_readme_claims.py`` suite enforces that README's advertised
percentages are never higher than what these fixtures actually deliver.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "plugin")
)

from crux import config, core
from crux.tokens import estimate_tokens

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES_DIR = os.path.join(ROOT, "examples", "fixtures")
README = os.path.join(ROOT, "README.md")

# (label, command, fixture file). Labels describe the real fixture contents.
CASES = [
    ("pytest (503 tests, 2 failures)", "pytest -v", "pytest_output.txt"),
    ("npm install (847 packages)", "npm install", "npm_install.txt"),
    ("kubectl get pods (49 pods)", "kubectl get pods", "kubectl_pods.txt"),
    ("git diff (5 files, large refactor)", "git diff", "large_git_diff.txt"),
    ("terraform plan (15 resource changes)", "terraform plan", "terraform_plan.txt"),
]

# Markers delimiting the auto-generated table inside README.md.
BEGIN = "<!-- BEGIN savings-table (generated by tools/generate_demo.py) -->"
END = "<!-- END savings-table -->"


def _fmt(n: int) -> str:
    return f"{n:,}"


def _saved(raw: int, out: int) -> int:
    return round((1 - out / raw) * 100) if raw > 0 else 0


def measure() -> list[dict]:
    """Run each fixture through the real pipeline under both profiles."""
    rows = []
    for label, command, fixture in CASES:
        path = os.path.join(FIXTURES_DIR, fixture)
        with open(path) as f:
            raw_text = f.read()
        raw = estimate_tokens(raw_text)

        results = {}
        for profile in ("balanced", "aggressive"):
            os.environ["CRUX_PROFILE"] = profile
            config.reload()
            results[profile] = estimate_tokens(core.compress(command, raw_text).compressed)
        os.environ.pop("CRUX_PROFILE", None)
        config.reload()

        rows.append(
            {
                "label": label,
                "raw": raw,
                "default": results["balanced"],
                "budget": results["aggressive"],
                "default_pct": _saved(raw, results["balanced"]),
                "budget_pct": _saved(raw, results["aggressive"]),
            }
        )
    return rows


def render_table(rows: list[dict]) -> str:
    """Render the markdown table that lives between the README markers."""
    out = [
        BEGIN,
        "",
        "| Command | Raw | Default | With a token budget |",
        "|---------|-----|---------|---------------------|",
    ]
    for r in rows:
        default = f"**{r['default_pct']}%**" if r["default_pct"] >= 50 else f"{r['default_pct']}%"
        budget = (
            f"**{r['budget_pct']}%**"
            if r["budget_pct"] > r["default_pct"]
            else f"{r['budget_pct']}%"
        )
        out.append(f"| {r['label']} | {_fmt(r['raw'])} tok | {default} | {budget} |")
    out += [
        "",
        "> Default keeps everything the agent needs and collapses pure redundancy "
        "(passing tests, install logs, pod tables). Diffs and plans are mostly *signal*, "
        "so they compress less by default — set `max_output_tokens` (or the `aggressive` "
        "profile) and the budget reducer compresses those too, while errors always survive.",
        "",
        END,
    ]
    return "\n".join(out)


def update_readme(table: str, *, check: bool) -> bool:
    """Splice the table into README between the markers. Returns True if unchanged."""
    with open(README) as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        raise SystemExit(f"README markers not found; expected {BEGIN!r} ... {END!r}")
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    new = head + table + tail
    if new == text:
        return True
    if check:
        return False
    with open(README, "w") as f:
        f.write(new)
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if README is out of date"
    )
    args = parser.parse_args()

    rows = measure()
    table = render_table(rows)

    print("\nCrux savings — measured from examples/fixtures/ via crux.core.compress\n")
    print(f"  {'Command':<40} {'Raw':>8} {'Default':>9} {'Budget':>9}")
    print(f"  {'-' * 40} {'-' * 8} {'-' * 9} {'-' * 9}")
    for r in rows:
        print(
            f"  {r['label']:<40} {_fmt(r['raw']):>8} "
            f"{str(r['default_pct']) + '%':>9} {str(r['budget_pct']) + '%':>9}"
        )
    print()

    unchanged = update_readme(table, check=args.check)
    if args.check:
        if unchanged:
            print("README savings table is up to date.")
        else:
            print("README savings table is STALE — run: python tools/generate_demo.py")
            raise SystemExit(1)
    else:
        print("README updated." if not unchanged else "README already up to date.")


if __name__ == "__main__":
    main()
